// Generated by DSDL2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: dronecan/mppt (2 types) + 0 referenced types of other root namespaces
// DSDL: OpenCyphal v1 .dsdl and DroneCAN .uavcan definitions
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.dsdl {
    /**
        <see cref = 'DsdlStream'/>
        <see cref = 'OutputEnable_Request'/>
        <see cref = 'OutputEnable_Response'/>
    */
    public interface dronecan_mppt {

        // Fallback caps for anything without an explicit [D(N)]; DSDL states every capacity, so this is only a floor.
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        /**
        Request of service mppt.OutputEnable
        Service to enable or disable the mppt output.
        */
        public class OutputEnable_Request {
            public const uint fixed_port_id = 240;
            bool enable;
            bool disable;
            // 6 bit(s) of `void` padding in the DSDL layout are not represented.
        }

        /**
        Response of service mppt.OutputEnable
        Service to enable or disable the mppt output.
        */
        public class OutputEnable_Response {
            public const uint fixed_port_id = 240;
            /**
            The new enable state after applying the request
            */
            bool enabled;
            // 7 bit(s) of `void` padding in the DSDL layout are not represented.
        }

        /**
        MPPT streaming data, transmitted at 1Hz
        */
        public class DsdlStream {
            public const uint fixed_port_id = 20009;
            /**
            over-voltage
            */
            public const byte OV_FAULT = 1;
            /**
            under-voltage
            */
            public const byte UV_FAULT = 2;
            /**
            over-current
            */
            public const byte OC_FAULT = 4;
            /**
            over-temperature
            */
            public const byte OT_FAULT = 8;
            byte fault_flags;
            /**
            [Celsius]
            */
            sbyte temperature;
            /**
            [Volt]
            */
            [Float16] float input_voltage;
            /**
            [Amp]
            */
            [Float16] float input_current;
            /**
            [Watt]
            */
            [Float16] float input_power;
            /**
            [Volt]
            */
            [Float16] float output_voltage;
            /**
            [Amp]
            */
            [Float16] float output_current;
            /**
            [Watt]
            */
            [Float16] float output_power;
        }

        // ═════════════════════════ demo topology ═════════════════════════

        // DSDL describes data types, not a topology: any node may publish any message subject and any node
        // may serve any service. The demo joins two nodes; Node_A is the service client, Node_B the server.

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Node_A : Host { }

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Node_B : Host { }

        interface Bus : Connects<Node_A, Node_B> {
            // Every message type of this root namespace, either direction, no state transition.
            [_____lr_____<DsdlStream>]
            struct Messages { }

            // Services: Node_A calls, Node_B responds (RPC shorthand: Call → Return → End).
            (L____________, OutputEnable_Response) OutputEnable(OutputEnable_Request req);
        }

        // ═════════════════════════ DSDL metadata attributes ═════════════════════════

        // AdHoc custom attributes: carried into the generated code as constants attached to the entity.

        /** DSDL type version (major, minor) from the file name. */
        public class VersionAttribute : Attribute { public VersionAttribute(long major, long minor) { } }

        /** @union: a tagged union, exactly one field is present. */
        public class UnionAttribute : Attribute { }

        /** @deprecated: the type is scheduled for removal. */
        public class DeprecatedAttribute : Attribute { }

        /** @sealed: no delimiter header, the layout is final. */
        public class SealedAttribute : Attribute { }

        /** @extent in bytes: the maximum serialized size future versions may grow to. */
        public class ExtentAttribute : Attribute { public ExtentAttribute(long bytes) { } }

        /** The DSDL field is a 16-bit IEEE 754 float (carried as float). */
        public class Float16Attribute : Attribute { }

        /** Explicit DSDL cast mode of the field ("truncated"; saturated is the default). */
        public class CastModeAttribute : Attribute { public CastModeAttribute(string mode) { } }

    }
}
