// Generated by DSDL2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: dronecan/cuav (1 types) + 0 referenced types of other root namespaces
// DSDL: OpenCyphal v1 .dsdl and DroneCAN .uavcan definitions
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.dsdl {
    /**
        <see cref = 'equipment.power.CBAT'/>
    */
    public interface dronecan_cuav {

        // Fallback caps for anything without an explicit [D(N)]; DSDL states every capacity, so this is only a floor.
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        /**
        Namespace cuav.equipment
        */
        public struct equipment {

            /**
            Namespace cuav.equipment.power
            */
            public struct power {

                /**
                support for CUAV Smart Battery on UAVCAN
                */
                public class CBAT {
                    public const uint fixed_port_id = 20300;
                    /**
                    The battery is currently used as a power supply
                    */
                    public const ushort STATUS_FLAG_IN_USE = 1;
                    /**
                    Charger is active
                    */
                    public const ushort STATUS_FLAG_CHARGING = 2;
                    /**
                    Charging complete, but the charger is still active
                    */
                    public const ushort STATUS_FLAG_CHARGED = 4;
                    /**
                    Battery temperature is above normal
                    */
                    public const ushort STATUS_FLAG_TEMP_HOT = 8;
                    /**
                    Battery temperature is below normal
                    */
                    public const ushort STATUS_FLAG_TEMP_COLD = 16;
                    /**
                    Safe operating area violation
                    */
                    public const ushort STATUS_FLAG_OVERLOAD = 32;
                    /**
                    This battery should not be used anymore (e.g. low SOH)
                    */
                    public const ushort STATUS_FLAG_BAD_BATTERY = 64;
                    /**
                    This battery requires maintenance (e.g. balancing, full recharge)
                    */
                    public const ushort STATUS_FLAG_NEED_SERVICE = 128;
                    /**
                    Battery management system/controller error, smart battery interface error
                    */
                    public const ushort STATUS_FLAG_BMS_ERROR = 256;
                    /**
                    Keep zero
                    */
                    public const ushort STATUS_FLAG_RESERVED_A = 512;
                    /**
                    Keep zero
                    */
                    public const ushort STATUS_FLAG_RESERVED_B = 1024;
                    /**
                    The surface temperature of the battery
                    */
                    float temperature;
                    /**
                    The total voltage of the battery
                    */
                    float voltage;
                    /**
                    Battery individual cell voltages
                    */
                    [D(15)] float[,,] voltage_cell;
                    /**
                    Number of cells
                    */
                    byte cell_count;
                    /**
                    The current flowing through the sense resistor
                    */
                    float current;
                    /**
                    The average current flowing through the sense resistor
                    */
                    float average_current;
                    /**
                    The average power of the current discharge
                    */
                    float average_power;
                    /**
                    The predicted charge or energy remaining in the battery
                    */
                    float available_energy;
                    /**
                    The compensated battery capacity remaining
                    */
                    float remaining_capacity;
                    /**
                    The compensated capacity of the battery when fully charged
                    */
                    float full_charge_capacity;
                    /**
                    The design capacity of the battery
                    */
                    float design_capacity;
                    /**
                    The predicted remaining battery life at the present rate of discharge, in minutes
                    */
                    ushort average_time_to_empty;
                    /**
                    The predicted remaining time until the battery reaches full charge, in minutes
                    */
                    ushort average_time_to_full;
                    /**
                    Health of the battery
                    */
                    [MinMax(0, 127)] byte state_of_health;
                    /**
                    Percent of the full charge [0, 100]
                    */
                    [MinMax(0, 127)] byte state_of_charge;
                    /**
                    max error, expected margin of error in % in the state-of-charge calculation with a range of 1 to 100%
                    */
                    [MinMax(0, 127)] byte max_error;
                    /**
                    serial number of the battery pack
                    */
                    ushort serial_number;
                    /**
                    manufacture date, part of serial number of the battery pack
                    */
                    ushort manufacture_date;
                    /**
                    number of discharge cycles the battery has experienced
                    */
                    ushort cycle_count; // physics: monotonic and large (counter/uptime/sequence) → varint LOSES past 268 435 455; keep fixed width
                    /**
                    Number of battery overdischarge
                    */
                    ushort over_discharge_count; // physics: monotonic and large (counter/uptime/sequence) → varint LOSES past 268 435 455; keep fixed width
                    /**
                    The amount of charge passing through the sense resistor
                    */
                    float passed_charge;
                    /**
                    Nominal voltage of the battery pack
                    */
                    float nominal_voltage;
                    /**
                    Power off event imminent indication, false if unknown
                    */
                    bool is_powering_off;
                    /**
                    interface error counter
                    */
                    ushort interface_error;
                    [MinMax(0, 2047)] ushort status_flags;
                }
            }
        }

        // ═════════════════════════ demo topology ═════════════════════════

        // DSDL describes data types, not a topology: any node may publish any message subject and any node
        // may serve any service. The demo joins two nodes; Node_A is the service client, Node_B the server.

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Node_A : Host { }

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Node_B : Host { }

        interface Bus : Connects<Node_A, Node_B> {
            // Every message type of this root namespace, either direction, no state transition.
            [_____lr_____<equipment.power.CBAT>]
            struct Messages { }
        }

        // ═════════════════════════ DSDL metadata attributes ═════════════════════════

        // AdHoc custom attributes: carried into the generated code as constants attached to the entity.

        /** DSDL type version (major, minor) from the file name. */
        public class VersionAttribute : Attribute { public VersionAttribute(long major, long minor) { } }

        /** @union: a tagged union, exactly one field is present. */
        public class UnionAttribute : Attribute { }

        /** @deprecated: the type is scheduled for removal. */
        public class DeprecatedAttribute : Attribute { }

        /** @sealed: no delimiter header, the layout is final. */
        public class SealedAttribute : Attribute { }

        /** @extent in bytes: the maximum serialized size future versions may grow to. */
        public class ExtentAttribute : Attribute { public ExtentAttribute(long bytes) { } }

        /** The DSDL field is a 16-bit IEEE 754 float (carried as float). */
        public class Float16Attribute : Attribute { }

        /** Explicit DSDL cast mode of the field ("truncated"; saturated is the default). */
        public class CastModeAttribute : Attribute { public CastModeAttribute(string mode) { } }

    }
}
