// Generated by DSDL2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: dronecan/ardupilot (14 types) + 1 referenced types of other root namespaces
// DSDL: OpenCyphal v1 .dsdl and DroneCAN .uavcan definitions
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.dsdl {
    /**
        <see cref = 'equipment.power.BatteryCells'/>
        <see cref = 'equipment.power.BatteryContinuous'/>
        <see cref = 'equipment.power.BatteryInfoAux'/>
        <see cref = 'equipment.power.BatteryPeriodic'/>
        <see cref = 'equipment.power.BatteryTag'/>
        <see cref = 'equipment.proximity_sensor.Proximity'/>
        <see cref = 'equipment.trafficmonitor.TrafficReport'/>
        <see cref = 'gnss.Heading'/>
        <see cref = 'gnss.MovingBaselineData'/>
        <see cref = 'gnss.RelPosHeading'/>
        <see cref = 'gnss.Status'/>
        <see cref = 'indication.Button'/>
        <see cref = 'indication.NotifyState'/>
        <see cref = 'indication.SafetyState'/>
    */
    public interface dronecan_ardupilot {

        // Fallback caps for anything without an explicit [D(N)]; DSDL states every capacity, so this is only a floor.
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        /**
        Namespace ardupilot.equipment
        */
        public struct equipment {

            /**
            Namespace ardupilot.equipment.power
            */
            public struct power {

                /**
                Battery cell voltages Rate: set by parameter on smart battery (default off)
                */
                public class BatteryCells {
                    public const uint fixed_port_id = 20012;
                    /**
                    [Volt]
                    */
                    [Float16, D(24)] float[,,] voltages;
                    /**
                    Index of the first cell in the array, index 0 is cells at array indices 0 - 23, index 24 is cells at array
                    indices 24 - 47, etc.
                    */
                    ushort index;
                }

                /**
                Battery data to be sent continuously
                */
                public class BatteryContinuous {
                    public const uint fixed_port_id = 20010;
                    public const uint STATUS_FLAG_READY_TO_USE = 1;
                    public const uint STATUS_FLAG_CHARGING = 2;
                    public const uint STATUS_FLAG_CELL_BALANCING = 4;
                    public const uint STATUS_FLAG_FAULT_CELL_IMBALANCE = 8;
                    public const uint STATUS_FLAG_AUTO_DISCHARGING = 16;
                    public const uint STATUS_FLAG_REQUIRES_SERVICE = 32;
                    public const uint STATUS_FLAG_BAD_BATTERY = 64;
                    public const uint STATUS_FLAG_PROTECTIONS_ENABLED = 128;
                    public const uint STATUS_FLAG_FAULT_PROTECTION_SYSTEM = 256;
                    public const uint STATUS_FLAG_FAULT_OVER_VOLT = 512;
                    public const uint STATUS_FLAG_FAULT_UNDER_VOLT = 1024;
                    public const uint STATUS_FLAG_FAULT_OVER_TEMP = 2048;
                    public const uint STATUS_FLAG_FAULT_UNDER_TEMP = 4096;
                    public const uint STATUS_FLAG_FAULT_OVER_CURRENT = 8192;
                    public const uint STATUS_FLAG_FAULT_SHORT_CIRCUIT = 16384;
                    public const uint STATUS_FLAG_FAULT_INCOMPATIBLE_VOLTAGE = 32768;
                    public const uint STATUS_FLAG_FAULT_INCOMPATIBLE_FIRMWARE = 65536;
                    public const uint STATUS_FLAG_FAULT_INCOMPATIBLE_CELLS_CONFIGURATION = 131072;
                    public const uint STATUS_FLAG_CAPACITY_RELATIVE_TO_FULL = 262144;
                    /**
                    [C]  : Pack mounted thermistor (preferably installed between cells), NAN: field not provided
                    */
                    [Float16] float temperature_cells;
                    /**
                    [C]  : Battery PCB temperature (likely output FET(s) or current sense resistor), NAN: field not provided
                    */
                    [Float16] float temperature_pcb;
                    /**
                    [C]  : Application dependent, NAN: field not provided
                    */
                    [Float16] float temperature_other;
                    /**
                    [A]  : Positive: defined as a discharge current. Negative: defined as a charging current, NAN: field not
                    provided
                    */
                    float current;
                    /**
                    [V]  : Battery voltage
                    */
                    float voltage;
                    /**
                    [%]  : The estimated state of charge, in percent remaining (0 - 100).
                    */
                    [Float16] float state_of_charge;
                    /**
                    : The physical location of the battery on the aircraft. 0: field not provided
                    */
                    byte slot_id;
                    /**
                    [Ah] : This is either the consumption since power-on or since the battery was full, depending on the value of
                    STATUS_FLAG_CAPACITY_RELATIVE_TO_FULL, NAN: field not provided
                    */
                    float capacity_consumed;
                    /**
                    : Fault, health, readiness, and other status indications
                    */
                    uint status_flags;
                }

                /**
                Auxilary Single battery info.
                This message is to be used in conjunction with uavcan/equipment/power/1092.BatteryInfo.uavcan
                */
                public class BatteryInfoAux {
                    public const uint fixed_port_id = 20004;
                    /**
                    Please ensure that this message is sent before the BatteryInfo which doesn't include the timestamp. The
                    following fields should contain the timestamp of the last current measurement. DSDL type uavcan.Timestamp
                    (microsecond timestamp) is modelled as an AdHoc DateTime.
                    */
                    DateTime timestamp;
                    /**
                    Battery individual cell voltages length of following field also used as cell count
                    [Volt]
                    */
                    [Float16, D(255)] float[,,] voltage_cell;
                    /**
                    Number of Charge/Discharge Cycles A charge cycle is defined as a complete discharge and charge. IE when the
                    system uses all of the battery's available energy capacity. Please note that this value doesn't mean that the
                    cycle count should be incremented at every charge. For example, if half of a battery's charge is used in one
                    run, and then recharged fully that is half of a cycle. If the same thing occurs again then the charge cycle
                    count would be incremented once, not twice.
                    */
                    ushort cycle_count; // physics: monotonic and large (counter/uptime/sequence) → varint LOSES past 268 435 455; keep fixed width
                    /**
                    Number of times the battery was discharged over the rated capacity
                    */
                    ushort over_discharge_count; // physics: monotonic and large (counter/uptime/sequence) → varint LOSES past 268 435 455; keep fixed width
                    /**
                    Max instantaneous current draw since last message
                    [Ampere]
                    */
                    [Float16] float max_current;
                    /**
                    Nominal voltage of the battery pack the nominal Voltage can be used for conversion between Wh and Ah if the
                    value of this field is 0, the conversion should be omitted.
                    [Volt]
                    */
                    [Float16] float nominal_voltage;
                    /**
                    Power off event imminent indication, false if unknown
                    */
                    bool is_powering_off;
                    /**
                    Identifies the battery within this vehicle, e.g. 0 - primary battery
                    */
                    byte battery_id;
                }

                /**
                Battery data to be sent statically upon request or periodically at a low rate Recommend that this message is
                sent at a maximum of 1Hz and nominally 0.2 Hz (IE: once every 5 seconds.)
                */
                public class BatteryPeriodic {
                    public const uint fixed_port_id = 20011;
                    /**
                    : Formatted as manufacturer_product, 0 terminated
                    */
                    [D(50)] byte[,,] name;
                    /**
                    : Serial number in ASCII characters, 0 terminated
                    */
                    [D(32)] byte[,,] serial_number;
                    /**
                    : Manufacture date (DDMMYYYY) in ASCII characters, 0 terminated
                    */
                    [D(9)] byte[,,] manufacture_date;
                    /**
                    [Ah] : Fully charged design capacity. 0: field not provided.
                    */
                    float design_capacity;
                    /**
                    : Number of battery cells in series. 0: field not provided.
                    */
                    byte cells_in_series;
                    /**
                    [V]  : Battery nominal voltage. Used for conversion between Wh and Ah. 0: field not provided.
                    */
                    [Float16] float nominal_voltage;
                    /**
                    [V]  : Minimum per-cell voltage when discharging. 0: field not provided.
                    */
                    [Float16] float discharge_minimum_voltage;
                    /**
                    [V]  : Minimum per-cell voltage when charging. 0: field not provided.
                    */
                    [Float16] float charging_minimum_voltage;
                    /**
                    [V]  : Maximum per-cell voltage when charged. 0: field not provided.
                    */
                    [Float16] float charging_maximum_voltage;
                    /**
                    [A]  : Maximum pack continuous charge current. 0: field not provided.
                    */
                    float charging_maximum_current;
                    /**
                    [A]  : Maximum pack continuous discharge current. 0: field not provided.
                    */
                    float discharge_maximum_current;
                    /**
                    [A]  : Maximum pack discharge burst current for 30 seconds. 0: field not provided
                    */
                    float discharge_maximum_burst_current;
                    /**
                    [Ah] : Predicted battery capacity when fully charged (accounting for battery degradation), NAN: field not
                    provided
                    */
                    float full_charge_capacity;
                    /**
                    : Lifetime count of the number of charge/discharge cycles (https://en.wikipedia.org/wiki/Charge_cycle).
                    UINT16_MAX: field not provided.
                    */
                    ushort cycle_count; // physics: monotonic and large (counter/uptime/sequence) → varint LOSES past 268 435 455; keep fixed width
                    /**
                    [%]  : State of Health (SOH) estimate, in percent (0 - 100). UINT8_MAX: field not provided.
                    */
                    byte state_of_health;
                }

                /**
                Battery tag information. This is broadcast by a battery tag device permanently attached to a battery to record
                the lifecycle of the battery
                */
                public class BatteryTag {
                    public const uint fixed_port_id = 20500;
                    /**
                    vendor supplied serial number
                    */
                    uint serial_number;
                    /**
                    number of cycles this battery has been through. Criteria for defining a cycle is vendor specific
                    */
                    uint num_cycles;
                    /**
                    number of hours that this battery has been running when vehicle is in an armed state
                    */
                    float armed_hours;
                    /**
                    battery capacity in milliAmpHours
                    */
                    uint battery_capacity_mAh;
                    /**
                    time of first use of battery with vehicle armed, in minutes since 1/1/1970
                    */
                    uint first_use_mins;
                    /**
                    time of most recent change to armed state, in minutes since 1/1/1970
                    */
                    uint last_arm_time_mins;
                }
            }

            /**
            Namespace ardupilot.equipment.proximity_sensor
            */
            public struct proximity_sensor {

                /**
                Proximity data
                */
                public class Proximity {
                    public const uint fixed_port_id = 21910;
                    /**
                    Distance is unknown
                    */
                    public const byte READING_TYPE_NO_DATA = 0;
                    /**
                    Distance field contains valid distance
                    */
                    public const byte READING_TYPE_NOT_CONNECTED = 1;
                    /**
                    Distance field contains valid reading for the sensor
                    */
                    public const byte READING_TYPE_GOOD = 2;
                    public const byte FLAGS_NONE = 0;
                    /**
                    Sensor ID
                    */
                    byte sensor_id;
                    /**
                    Sensor Status
                    */
                    [MinMax(0, 7)] byte reading_type;
                    /**
                    Reserved
                    */
                    [MinMax(0, 31)] byte flags;
                    /**
                    Degrees in body frame
                    */
                    [Float16] float yaw;
                    /**
                    Degrees in body frame
                    */
                    [Float16] float pitch;
                    /**
                    Meters
                    */
                    [Float16] float distance;
                }
            }

            /**
            Namespace ardupilot.equipment.trafficmonitor
            */
            public struct trafficmonitor {

                public class TrafficReport {
                    public const uint fixed_port_id = 20790;
                    /**
                    Traffic source
                    */
                    public const byte SOURCE_ADSB = 0;
                    public const byte SOURCE_ADSB_UAT = 1;
                    public const byte SOURCE_FLARM = 2;
                    /**
                    Traffic type
                    */
                    public const byte TRAFFIC_TYPE_UNKNOWN = 0;
                    public const byte TRAFFIC_TYPE_LIGHT = 1;
                    public const byte TRAFFIC_TYPE_SMALL = 2;
                    public const byte TRAFFIC_TYPE_LARGE = 3;
                    public const byte TRAFFIC_TYPE_HIGH_VORTEX_LARGE = 4;
                    public const byte TRAFFIC_TYPE_HEAVY = 5;
                    public const byte TRAFFIC_TYPE_HIGHLY_MANUV = 6;
                    public const byte TRAFFIC_TYPE_ROTOCRAFT = 7;
                    public const byte TRAFFIC_TYPE_GLIDER = 9;
                    public const byte TRAFFIC_TYPE_LIGHTER_THAN_AIR = 10;
                    public const byte TRAFFIC_TYPE_PARACHUTE = 11;
                    public const byte TRAFFIC_TYPE_ULTRA_LIGHT = 12;
                    public const byte TRAFFIC_TYPE_UAV = 14;
                    public const byte TRAFFIC_TYPE_SPACE = 15;
                    public const byte TRAFFIC_TYPE_EMERGENCY_SURFACE = 17;
                    public const byte TRAFFIC_TYPE_SERVICE_SURFACE = 18;
                    public const byte TRAFFIC_TYPE_POINT_OBSTACLE = 19;
                    /**
                    Altitude type
                    */
                    public const byte ALT_TYPE_ALT_UNKNOWN = 0;
                    public const byte ALT_TYPE_PRESSURE_AMSL = 1;
                    public const byte ALT_TYPE_WGS84 = 2;
                    /**
                    Network-synchronized timestamp, 0 if not available. Note: not necessarily a UTC time. DSDL type
                    uavcan.Timestamp (microsecond timestamp) is modelled as an AdHoc DateTime.
                    */
                    DateTime timestamp;
                    /**
                    icao address
                    */
                    uint icao_address;
                    /**
                    Time since last communication in seconds
                    */
                    ushort tslc;
                    /**
                    Traffic position in lat-lon-alt. Check alt_type for altitude datum
                    */
                    int latitude_deg_1e7;
                    int longitude_deg_1e7;
                    float alt_m;
                    /**
                    Traffic heading in radians. Course over ground if heading is unavailable. 0 if neither are available.
                    */
                    [Float16] float heading;
                    /**
                    Traffic velocity in m/s (NED frame)
                    */
                    [Float16, D(3)] float[] velocity;
                    /**
                    Traffic squawk code
                    */
                    ushort squawk;
                    /**
                    Traffic callsign
                    */
                    [D(9)] byte[] callsign;
                    [MinMax(0, 7)] byte source;
                    [MinMax(0, 31)] byte traffic_type;
                    [MinMax(0, 127)] byte alt_type;
                    /**
                    Validity flags
                    */
                    bool lat_lon_valid;
                    bool heading_valid;
                    bool velocity_valid;
                    bool callsign_valid;
                    bool ident_valid;
                    bool simulated_report;
                    bool vertical_velocity_valid;
                    bool baro_valid;
                }
            }
        }

        /**
        Namespace ardupilot.gnss
        */
        public struct gnss {

            public class Heading {
                public const uint fixed_port_id = 20002;
                bool heading_valid;
                bool heading_accuracy_valid;
                [Float16] float heading_rad;
                [Float16] float heading_accuracy_rad;
            }

            public class MovingBaselineData {
                public const uint fixed_port_id = 20005;
                /**
                length of data is set per the number of bytes for pkt in libraries/AP_GPS/RTCM3_Parser.h
                */
                [D(300)] byte[,,] data;
            }

            public class RelPosHeading {
                public const uint fixed_port_id = 20006;
                /**
                timestamp on the gps message DSDL type uavcan.Timestamp (microsecond timestamp) is modelled as an AdHoc
                DateTime.
                */
                DateTime timestamp;
                bool reported_heading_acc_available;
                float reported_heading_deg;
                float reported_heading_acc_deg;
                [Float16] float relative_distance_m;
                [Float16] float relative_down_pos_m;
            }

            public class Status {
                public const uint fixed_port_id = 20003;
                /**
                Status is actually a bitmask, due to encoding issues pretend it's just a field, and leave it up to the
                application do decode it) GNSS system is doing any onboard logging
                */
                public const uint STATUS_LOGGING = 1;
                /**
                GNSS system is in a reasonable state to allow the system to arm
                */
                public const uint STATUS_ARMABLE = 2;
                /**
                Node specific GNSS error codes, primarily available for logging and diagnostics
                */
                uint error_codes;
                /**
                GNSS system is self assesd as healthy
                */
                bool healthy;
                [MinMax(0, 8388607)] uint status;
            }
        }

        /**
        Namespace ardupilot.indication
        */
        public struct indication {

            /**
            support for buttons on UAVCAN while a button is being pressed this message should be sent at 10Hz
            */
            public class Button {
                public const uint fixed_port_id = 20001;
                public const byte BUTTON_SAFETY = 1;
                byte button;
                /**
                number of 0.1s units the button has been pressed for. If over 255 then send 255
                */
                byte press_time;
            }

            public class NotifyState {
                public const uint fixed_port_id = 20007;
                public const byte VEHICLE_STATE_INITIALISING = 0;
                public const byte VEHICLE_STATE_ARMED = 1;
                public const byte VEHICLE_STATE_FLYING = 2;
                public const byte VEHICLE_STATE_PREARM = 3;
                public const byte VEHICLE_STATE_PREARM_GPS = 4;
                public const byte VEHICLE_STATE_SAVE_TRIM = 5;
                public const byte VEHICLE_STATE_ESC_CALIBRATION = 6;
                public const byte VEHICLE_STATE_FAILSAFE_RADIO = 7;
                public const byte VEHICLE_STATE_FAILSAFE_BATT = 8;
                public const byte VEHICLE_STATE_FAILSAFE_GCS = 9;
                public const byte VEHICLE_STATE_CHUTE_RELEASED = 10;
                public const byte VEHICLE_STATE_EKF_BAD = 11;
                public const byte VEHICLE_STATE_FW_UPDATE = 12;
                public const byte VEHICLE_STATE_MAGCAL_RUN = 13;
                public const byte VEHICLE_STATE_LEAK_DET = 14;
                public const byte VEHICLE_STATE_GPS_FUSION = 15;
                public const byte VEHICLE_STATE_GPS_GLITCH = 16;
                public const byte VEHICLE_STATE_POS_ABS_AVAIL = 17;
                public const byte VEHICLE_STATE_LOST = 18;
                public const byte VEHICLE_STATE_THROW_READY = 19;
                public const byte VEHICLE_STATE_POWERING_OFF = 20;
                public const byte VEHICLE_STATE_VIDEO_RECORDING = 21;
                public const byte VEHICLE_STATE_IS_LANDING = 22;
                public const byte VEHICLE_STATE_IS_TAKING_OFF = 23;
                /**
                beware that the auxiliary data indicated by ARDUPILOT_INDICATION_NOTIFYSTATE_VEHICLE_YAW_EARTH_CENTIDEGREES is
                strange; it's number of degrees *counter-clockwise* from North:
                */
                public const byte VEHICLE_YAW_EARTH_CENTIDEGREES = 0;
                /**
                set the type of aux data to be sent
                */
                byte aux_data_type;
                /**
                bytes containing packed auxiliary data placing it first so we don't do TAO
                */
                [D(255)] byte[,,] aux_data;
                /**
                Current Vehicle State Mask
                */
                ulong vehicle_state;
            }

            /**
            support for Safety LED on UAVCAN
            */
            public class SafetyState {
                public const uint fixed_port_id = 20000;
                public const byte STATUS_SAFETY_ON = 0;
                public const byte STATUS_SAFETY_OFF = 255;
                byte status;
            }
        }

        /**
        Namespace uavcan
        */
        public struct uavcan {

            /**
            Global timestamp in microseconds, 7 bytes.
            Use this data type for timestamp fields in messages, like follows: uavcan.Timestamp timestamp
            Referenced from another root namespace; used as a sub-pack only.
            Fields of this DSDL type are emitted as an AdHoc DateTime, so this pack itself is normally unused.
            */
            public class Timestamp {
                public const ulong UNKNOWN = 0;
                /**
                Microseconds
                */
                [CastMode("truncated"), MinMax(0, 72057594037927935)] ulong usec;
            }
        }

        // ═════════════════════════ demo topology ═════════════════════════

        // DSDL describes data types, not a topology: any node may publish any message subject and any node
        // may serve any service. The demo joins two nodes; Node_A is the service client, Node_B the server.

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Node_A : Host { }

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Node_B : Host { }

        interface Bus : Connects<Node_A, Node_B> {
            // Every message type of this root namespace, either direction, no state transition.
            [_____lr_____<(equipment.power.BatteryCells, equipment.power.BatteryContinuous, equipment.power.BatteryInfoAux, equipment.power.BatteryPeriodic, equipment.power.BatteryTag, equipment.proximity_sensor.Proximity, equipment.trafficmonitor.TrafficReport, gnss.Heading, gnss.MovingBaselineData, gnss.RelPosHeading, gnss.Status, indication.Button, indication.NotifyState, indication.SafetyState)>]
            struct Messages { }
        }

        // ═════════════════════════ DSDL metadata attributes ═════════════════════════

        // AdHoc custom attributes: carried into the generated code as constants attached to the entity.

        /** DSDL type version (major, minor) from the file name. */
        public class VersionAttribute : Attribute { public VersionAttribute(long major, long minor) { } }

        /** @union: a tagged union, exactly one field is present. */
        public class UnionAttribute : Attribute { }

        /** @deprecated: the type is scheduled for removal. */
        public class DeprecatedAttribute : Attribute { }

        /** @sealed: no delimiter header, the layout is final. */
        public class SealedAttribute : Attribute { }

        /** @extent in bytes: the maximum serialized size future versions may grow to. */
        public class ExtentAttribute : Attribute { public ExtentAttribute(long bytes) { } }

        /** The DSDL field is a 16-bit IEEE 754 float (carried as float). */
        public class Float16Attribute : Attribute { }

        /** Explicit DSDL cast mode of the field ("truncated"; saturated is the default). */
        public class CastModeAttribute : Attribute { public CastModeAttribute(string mode) { } }

    }
}
