// Generated by DSDL2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: dronecan/com (29 types) + 0 referenced types of other root namespaces
// DSDL: OpenCyphal v1 .dsdl and DroneCAN .uavcan definitions
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.dsdl {
    /**
        <see cref = 'hex.equipment.flow.Measurement'/>
        <see cref = 'himark.servo.ServoCmd'/>
        <see cref = 'himark.servo.ServoInfo'/>
        <see cref = 'hobbywing.esc.GetEscID'/>
        <see cref = 'hobbywing.esc.GetMaintenanceInformation_Request'/>
        <see cref = 'hobbywing.esc.GetMaintenanceInformation_Response'/>
        <see cref = 'hobbywing.esc.GetMajorConfig_Request'/>
        <see cref = 'hobbywing.esc.GetMajorConfig_Response'/>
        <see cref = 'hobbywing.esc.RawCommand'/>
        <see cref = 'hobbywing.esc.SelfTest_Request'/>
        <see cref = 'hobbywing.esc.SelfTest_Response'/>
        <see cref = 'hobbywing.esc.SetAngle_Request'/>
        <see cref = 'hobbywing.esc.SetAngle_Response'/>
        <see cref = 'hobbywing.esc.SetBaud_Request'/>
        <see cref = 'hobbywing.esc.SetBaud_Response'/>
        <see cref = 'hobbywing.esc.SetDirection_Request'/>
        <see cref = 'hobbywing.esc.SetDirection_Response'/>
        <see cref = 'hobbywing.esc.SetID_Request'/>
        <see cref = 'hobbywing.esc.SetID_Response'/>
        <see cref = 'hobbywing.esc.SetLED_Request'/>
        <see cref = 'hobbywing.esc.SetLED_Response'/>
        <see cref = 'hobbywing.esc.SetReportingFrequency_Request'/>
        <see cref = 'hobbywing.esc.SetReportingFrequency_Response'/>
        <see cref = 'hobbywing.esc.SetThrottleSource_Request'/>
        <see cref = 'hobbywing.esc.SetThrottleSource_Response'/>
        <see cref = 'hobbywing.esc.StatusMsg1'/>
        <see cref = 'hobbywing.esc.StatusMsg2'/>
        <see cref = 'hobbywing.esc.StatusMsg3'/>
        <see cref = 'tmotor.esc.FocCtrl'/>
        <see cref = 'tmotor.esc.PUSHCAN'/>
        <see cref = 'tmotor.esc.PUSHSCI'/>
        <see cref = 'tmotor.esc.ParamCfg'/>
        <see cref = 'tmotor.esc.ParamGet'/>
        <see cref = 'volz.servo.ActuatorStatus'/>
        <see cref = 'xacti.CopterAttStatus'/>
        <see cref = 'xacti.GimbalAttitudeStatus'/>
        <see cref = 'xacti.GimbalControlData'/>
        <see cref = 'xacti.GnssStatus'/>
        <see cref = 'xacti.GnssStatusReq'/>
    */
    public interface dronecan_com {

        // Fallback caps for anything without an explicit [D(N)]; DSDL states every capacity, so this is only a floor.
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        /**
        Namespace com.hex
        */
        public struct hex {

            /**
            Namespace com.hex.equipment
            */
            public struct equipment {

                /**
                Namespace com.hex.equipment.flow
                */
                public struct flow {

                    public class Measurement {
                        public const uint fixed_port_id = 20200;
                        /**
                        Integration Interval in seconds
                        */
                        float integration_interval;
                        /**
                        Integrated Gyro Data in radians
                        */
                        [D(2)] float[] rate_gyro_integral;
                        /**
                        Integrated LOS Data in radians
                        */
                        [D(2)] float[] flow_integral;
                        /**
                        Flow Data Quality Lowest(0)-Highest(255) Unitless
                        */
                        byte quality;
                    }
                }
            }
        }

        /**
        Namespace com.himark
        */
        public struct himark {

            /**
            Namespace com.himark.servo
            */
            public struct servo {

                /**
                Himark servo commands it is not recommended that anyone implement this message. It is here as a placeholder
                for existing Himark servos
                */
                public class ServoCmd {
                    public const uint fixed_port_id = 2018;
                    public const string DATA_TYPE_SIGNATURE = "0x5D09E48551CE9194";
                    [MinMax(0, 1023), D(17)] ushort[,,] cmd;
                }

                /**
                Himark servo feedback information it is not recommended that anyone implement this message. It is here as a
                placeholder for existing Himark servos
                */
                public class ServoInfo {
                    public const uint fixed_port_id = 2019;
                    public const string DATA_TYPE_SIGNATURE = "0xCA8F4B8F97D23B57";
                    public const byte ERROR_STATUS_NO_ERROR = 0;
                    public const byte ERROR_STATUS_DATA_ERROR = 1;
                    /**
                    servo ID from 0 to 17
                    */
                    [MinMax(0, 31)] byte servo_id;
                    /**
                    current commanded input, range 700 to 2300, 1 LSB/us
                    */
                    [MinMax(0, 4095)] ushort pwm_input;
                    /**
                    commanded position from -18000 to 18000, 1 LSB == 0.01 degrees
                    */
                    short pos_cmd;
                    /**
                    sensed position from -18000 to 18000, 1 LSB == 0.01 degrees
                    */
                    short pos_sensor;
                    /**
                    voltage, range 0 to 4095, 1 LSB == 0.01V
                    */
                    [MinMax(0, 4095)] ushort voltage;
                    /**
                    current, range 0 to 1023, 1 LSB == 0.01A
                    */
                    [MinMax(0, 1023)] ushort current;
                    /**
                    PCB temperature, range 0 to 1023, 1 LSB == 0.2 degrees Celsius, temp = pcb_tem*0.2-40
                    */
                    [MinMax(0, 1023)] ushort pcb_temp;
                    /**
                    motor temperature, range 0 to 1023, 1 LSB == 0.2 degrees Celsius, temp = motor_tem*0.2-40
                    */
                    [MinMax(0, 1023)] ushort motor_temp;
                    [MinMax(0, 31)] byte error_status;
                }
            }
        }

        /**
        Namespace com.hobbywing
        */
        public struct hobbywing {

            /**
            Namespace com.hobbywing.esc
            */
            public struct esc {

                public class GetEscID {
                    public const uint fixed_port_id = 20013;
                    public const string DATA_TYPE_SIGNATURE = "0x4E2D";
                    [D(3)] byte[,,] payload;
                }

                /**
                Request of service com.hobbywing.esc.GetMaintenanceInformation
                */
                public class GetMaintenanceInformation_Request {
                    public const uint fixed_port_id = 241;
                    public const string DATA_TYPE_SIGNATURE = "0xb81dbd4ec9a5977d";
                    public const byte OPTION_CLEAR = 1;
                    byte option;
                }

                /**
                Response of service com.hobbywing.esc.GetMaintenanceInformation
                */
                public class GetMaintenanceInformation_Response {
                    public const uint fixed_port_id = 241;
                    uint total_rotation_time_min;
                    [MinMax(0, 16777215)] uint time_since_maintainence_min;
                }

                /**
                Request of service com.hobbywing.esc.GetMajorConfig
                */
                public class GetMajorConfig_Request {
                    public const uint fixed_port_id = 242;
                    public const string DATA_TYPE_SIGNATURE = "0x1506774da3930bfd";
                    byte option;
                }

                /**
                Response of service com.hobbywing.esc.GetMajorConfig
                */
                public class GetMajorConfig_Response {
                    public const uint fixed_port_id = 242;
                    bool direction;
                    bool throttle_source;
                    [MinMax(0, 63)] byte throttle_channel;
                    [MinMax(0, 31)] byte led_status;
                    [MinMax(0, 7)] byte led_color;
                    [MinMax(0, 15)] byte MSG2_rate;
                    [MinMax(0, 15)] byte MSG1_rate;
                    ushort positioning_angle;
                    [D(2)] byte[] reserved;
                }

                public class RawCommand {
                    public const uint fixed_port_id = 20100;
                    public const string DATA_TYPE_SIGNATURE = "0xbdf086c79f6640ad";
                    [MinMax(-8192, 8191), D(8)] short[,,] command;
                }

                /**
                Request of service com.hobbywing.esc.SelfTest
                */
                public class SelfTest_Request {
                    public const uint fixed_port_id = 216;
                    public const string DATA_TYPE_SIGNATURE = "0xc48d4de61c5295df";
                }

                /**
                Response of service com.hobbywing.esc.SelfTest
                */
                public class SelfTest_Response {
                    public const uint fixed_port_id = 216;
                    public const byte STATUS_PASS = 0;
                    public const byte STATUS_FAIL = 1;
                    byte status;
                }

                /**
                Request of service com.hobbywing.esc.SetAngle
                */
                public class SetAngle_Request {
                    public const uint fixed_port_id = 217;
                    public const string DATA_TYPE_SIGNATURE = "0x81d9b10761c28e0a";
                    byte option;
                    ushort angle;
                }

                /**
                Response of service com.hobbywing.esc.SetAngle
                */
                public class SetAngle_Response {
                    public const uint fixed_port_id = 217;
                    byte option;
                    [D(2)] ushort[,,] angle;
                }

                /**
                Request of service com.hobbywing.esc.SetBaud
                */
                public class SetBaud_Request {
                    public const uint fixed_port_id = 211;
                    public const string DATA_TYPE_SIGNATURE = "0xada98653b52de435";
                    public const byte BAUD_1MBPS = 0;
                    public const byte BAUD_500KBPS = 1;
                    public const byte BAUD_250KBPS = 2;
                    public const byte BAUD_200KBPS = 3;
                    public const byte BAUD_100KBPS = 4;
                    public const byte BAUD_50KBPS = 5;
                    byte baud;
                }

                /**
                Response of service com.hobbywing.esc.SetBaud
                */
                public class SetBaud_Response {
                    public const uint fixed_port_id = 211;
                }

                /**
                Request of service com.hobbywing.esc.SetDirection
                */
                public class SetDirection_Request {
                    public const uint fixed_port_id = 213;
                    public const string DATA_TYPE_SIGNATURE = "0x9d793111d262ba68";
                    public const byte DIRECTION_CLOCKWISE = 0;
                    public const byte DIRECTION_COUNTER_CLOCKWISE = 1;
                    public const byte DIRECTION_QUERY = 255;
                    byte direction;
                }

                /**
                Response of service com.hobbywing.esc.SetDirection
                */
                public class SetDirection_Response {
                    public const uint fixed_port_id = 213;
                    byte direction;
                }

                /**
                Request of service com.hobbywing.esc.SetID
                */
                public class SetID_Request {
                    public const uint fixed_port_id = 210;
                    public const string DATA_TYPE_SIGNATURE = "0xc323cb5e9ec2b6f7";
                    byte node_id;
                    byte throttle_channel;
                }

                /**
                Response of service com.hobbywing.esc.SetID
                */
                public class SetID_Response {
                    public const uint fixed_port_id = 210;
                    byte node_id;
                    byte throttle_channel;
                }

                /**
                Request of service com.hobbywing.esc.SetLED
                */
                public class SetLED_Request {
                    public const uint fixed_port_id = 212;
                    public const string DATA_TYPE_SIGNATURE = "0xb493bd48c0853ee5";
                    public const byte OPTION_SAVE = 1;
                    public const byte COLOR_R = 4;
                    public const byte COLOR_G = 2;
                    public const byte COLOR_B = 1;
                    public const byte BLINK_OFF = 0;
                    public const byte BLINK_1HZ = 1;
                    public const byte BLINK_2HZ = 2;
                    public const byte BLINK_5HZ = 5;
                    byte option;
                    byte color;
                    byte blink;
                }

                /**
                Response of service com.hobbywing.esc.SetLED
                */
                public class SetLED_Response {
                    public const uint fixed_port_id = 212;
                    byte option;
                    byte color;
                    byte blink;
                }

                /**
                Request of service com.hobbywing.esc.SetReportingFrequency
                */
                public class SetReportingFrequency_Request {
                    public const uint fixed_port_id = 214;
                    public const string DATA_TYPE_SIGNATURE = "0x1fd0404420983deb";
                    public const byte OPTION_READ = 0;
                    public const byte OPTION_WRITE = 1;
                    public const byte RATE_500HZ = 1;
                    public const byte RATE_250HZ = 2;
                    public const byte RATE_200HZ = 3;
                    public const byte RATE_100HZ = 4;
                    public const byte RATE_50HZ = 5;
                    public const byte RATE_20HZ = 6;
                    public const byte RATE_10HZ = 7;
                    public const byte RATE_1HZ = 8;
                    public const byte RATE_0HZ = 9;
                    byte option;
                    ushort MSG_ID;
                    byte rate;
                }

                /**
                Response of service com.hobbywing.esc.SetReportingFrequency
                */
                public class SetReportingFrequency_Response {
                    public const uint fixed_port_id = 214;
                    byte option;
                    ushort MSG_ID;
                    byte rate;
                }

                /**
                Request of service com.hobbywing.esc.SetThrottleSource
                */
                public class SetThrottleSource_Request {
                    public const uint fixed_port_id = 215;
                    public const string DATA_TYPE_SIGNATURE = "0x0c248faaefe5e29a";
                    public const byte SOURCE_CAN_DIGITAL = 0;
                    public const byte SOURCE_PWM = 1;
                    byte source;
                }

                /**
                Response of service com.hobbywing.esc.SetThrottleSource
                */
                public class SetThrottleSource_Response {
                    public const uint fixed_port_id = 215;
                    byte source;
                }

                public class StatusMsg1 {
                    public const uint fixed_port_id = 20050;
                    public const string DATA_TYPE_SIGNATURE = "0x0813b3e2c4ad670e";
                    ushort rpm;
                    ushort pwm;
                    ushort status;
                }

                public class StatusMsg2 {
                    public const uint fixed_port_id = 20051;
                    public const string DATA_TYPE_SIGNATURE = "0x1675da01c3b91297";
                    /**
                    0.1V
                    */
                    short input_voltage;
                    /**
                    0.1A
                    */
                    short current;
                    /**
                    degC
                    */
                    byte temperature;
                }

                public class StatusMsg3 {
                    public const uint fixed_port_id = 20052;
                    public const string DATA_TYPE_SIGNATURE = "0x24919cd1eb34ece9";
                    byte MOS_T;
                    byte CAP_T;
                    byte Motor_T;
                }
            }
        }

        /**
        Namespace com.tmotor
        */
        public struct tmotor {

            /**
            Namespace com.tmotor.esc
            */
            public struct esc {

                /**
                Generic ESC status.
                */
                public class FocCtrl {
                    public const uint fixed_port_id = 1035;
                    public const string DATA_TYPE_SIGNATURE = "0x598143612FBC000B";
                    byte esc_index;
                    byte esc_mode;
                    byte esc_fdb_rate;
                    byte esc_cmd;
                    int esc_cmd_val;
                }

                /**
                Generic ESC status.
                */
                public class PUSHCAN {
                    public const uint fixed_port_id = 1039;
                    public const string DATA_TYPE_SIGNATURE = "0xAACF9B4B2577BC6E";
                    /**
                    data sequence
                    */
                    uint data_sequence;
                    [D(255)] byte[,,] data;
                }

                /**
                Generic ESC SCI DATA.
                */
                public class PUSHSCI {
                    public const uint fixed_port_id = 1038;
                    public const string DATA_TYPE_SIGNATURE = "0xCE2B6D6B6BDC0AE8";
                    /**
                    data sequence
                    */
                    uint data_sequence;
                    [D(255)] byte[,,] data;
                }

                /**
                1033.ParamCfg.uavcan parameter setting
                */
                public class ParamCfg {
                    public const uint fixed_port_id = 1033;
                    public const string DATA_TYPE_SIGNATURE = "0x948F5E0B33E0EDEE";
                    byte esc_index;
                    uint esc_uuid;
                    ushort esc_id_set;
                    ushort esc_ov_threshold;
                    ushort esc_oc_threshold;
                    ushort esc_ot_threshold;
                    ushort esc_acc_threshold;
                    ushort esc_dacc_threshold;
                    short esc_rotate_dir;
                    byte esc_timing;
                    byte esc_signal_priority;
                    ushort esc_led_mode;
                    byte esc_can_rate;
                    ushort esc_fdb_rate;
                    byte esc_save_option;
                }

                /**
                1033.ParamGet.uavcan param get pack
                */
                public class ParamGet {
                    public const uint fixed_port_id = 1332;
                    public const string DATA_TYPE_SIGNATURE = "0x462875A0ED874302";
                    byte esc_index;
                    uint esc_uuid;
                    ushort esc_id_req;
                    ushort esc_ov_threshold;
                    ushort esc_oc_threshold;
                    ushort esc_ot_threshold;
                    ushort esc_acc_threshold;
                    ushort esc_dacc_threshold;
                    short esc_rotate_dir;
                    byte esc_timing;
                    ushort esc_startup_times;
                    uint esc_startup_duration;
                    uint esc_product_date;
                    uint esc_error_count;
                    byte esc_signal_priority;
                    ushort esc_led_mode;
                    byte esc_can_rate;
                    ushort esc_fdb_rate;
                    byte esc_save_option;
                    [D(32)] byte[,,] rsvd;
                }
            }
        }

        /**
        Namespace com.volz
        */
        public struct volz {

            /**
            Namespace com.volz.servo
            */
            public struct servo {

                /**
                Volz servo feedback.
                */
                public class ActuatorStatus {
                    public const uint fixed_port_id = 20020;
                    /**
                    Unique actuator ID (1..15)
                    */
                    byte actuator_id;
                    /**
                    Actual servo position in radians
                    */
                    [Float16] float actual_position;
                    /**
                    Current: unsigned, 8-bit value, one count = 0.025 A
                    */
                    byte current;
                    /**
                    Supply voltage: unsigned, 8-bit value, one count = 0.2 V
                    */
                    byte voltage;
                    /**
                    Motor PWM: unsigned, 8-bit value, 0 = 0% Motor power, 255 = 100% Motor Power
                    */
                    byte motor_pwm;
                    /**
                    Motor temperature: unsigned 8-bit value, 0 = -50C, 255 = sensor error, one count = one degree
                    */
                    byte motor_temperature;
                }
            }
        }

        /**
        Namespace com.xacti
        */
        public struct xacti {

            /**
            Xacti specific vehicle attitude provided to camera gimbal send periodically 5~10Hz.
            quaternion_wxyz_e4[0] = q.w	(or q.q0) * 1e4f quaternion_wxyz_e4[1] = q.x	(or q.q1) * 1e4f
            quaternion_wxyz_e4[2] = q.y	(or q.q2) * 1e4f quaternion_wxyz_e4[3] = q.z	(or q.q3) * 1e4f
            */
            public class CopterAttStatus {
                public const uint fixed_port_id = 20407;
                public const string DATA_TYPE_SIGNATURE = "0x6C1F30F1893763B1";
                /**
                vehicle attitude quaternion * 1e4
                */
                [D(4)] short[] quaternion_wxyz_e4;
                /**
                reserved
                */
                [Float16, D(2)] float[,,] reserved;
            }

            /**
            Xacti camera gimbal attitude status
            */
            public class GimbalAttitudeStatus {
                public const uint fixed_port_id = 20402;
                public const string DATA_TYPE_SIGNATURE = "0xEB428B6C25832692";
                /**
                gimbal attitude in euler centi-degrees from -18000 to +18000
                */
                short gimbal_roll;
                short gimbal_pitch;
                short gimbal_yaw;
                short magneticencoder_roll;
                short magneticencoder_pitch;
                short magneticencoder_yaw;
            }

            /**
            Xacti camera gimbal control
            */
            public class GimbalControlData {
                public const uint fixed_port_id = 20554;
                public const string DATA_TYPE_SIGNATURE = "0x3B058FA5B150C5BE";
                /**
                pitch and yaw command type 0: unused 2: angle control 3: angular velocity control
                */
                byte pitch_cmd_type;
                byte yaw_cmd_type;
                /**
                pitch command value if cmd_type is 0 these values are ignored if cmd_type is 2 (angle control) scale is
                centi-degrees. Range is -115 deg (e.g. -11500) to 45 (e.g. 4500). Positive values point gimbal upwards if
                cmd_type is 3 (angular velocity control), scale is centi-degrees/sec values are unsigned but gimbal will cast
                to signed
                */
                ushort pitch_cmd_value;
                /**
                yaw command value if cmd_type is 0 these values are ignored if cmd_type is 2 (angle control) scale is
                centi-degrees. Yaw range is -85 deg (e.g. -8500) to +85 deg (e.g. +8500).  Positive is clockwise if cmd_type
                is 3 (angular velocity control), scale is centi-degrees/sec values are unsigned but gimbal will cast to signed
                */
                ushort yaw_cmd_value;
            }

            /**
            Xacti GNSS status
            */
            public class GnssStatus {
                public const uint fixed_port_id = 20305;
                public const string DATA_TYPE_SIGNATURE = "0x3413AC5D3E1DCBE3";
                /**
                GPS status 0: Invalid.  all fields except order and remain_buffer should be zero 1: No CAM_SYNC requests. all
                other fields should be zero 2: Valid
                */
                byte gps_status;
                /**
                order request sequence number in range from 0 to 21.  incremented each time will be 0 in response to a
                GnssStatusReq with 'requirement' field of 0 (clear buffer)
                */
                byte order;
                /**
                remain_buffer number of buffers remaining in range from 0 to 21.  0 is empty
                */
                byte remain_buffer;
                /**
                UTCD year, month, day, hour minute and second
                2023 ~
                */
                ushort utc_year;
                /**
                1 ~ 12
                */
                byte utc_month;
                /**
                1 ~ 31
                */
                byte utc_day;
                /**
                0 ~ 23
                */
                byte utc_hour;
                /**
                0 ~ 59
                */
                byte utc_minute;
                /**
                0 ~ below 60
                */
                float utc_seconds;
                /**
                latitude, longitude, altitude (in meters, AMSL)
                degrees -90 ~ +90
                */
                double latitude;
                /**
                degrees -180 ~ +180
                */
                double longitude;
                /**
                meters above sea level, AMSL
                */
                float altitude;
            }

            /**
            Xacti GNSS status request
            */
            public class GnssStatusReq {
                public const uint fixed_port_id = 20306;
                public const string DATA_TYPE_SIGNATURE = "0x60F5464E1CA03449";
                /**
                requirement 0: clear buffer command 1 ~ 21: request sequence
                */
                byte requirement;
            }
        }

        // ═════════════════════════ demo topology ═════════════════════════

        // DSDL describes data types, not a topology: any node may publish any message subject and any node
        // may serve any service. The demo joins two nodes; Node_A is the service client, Node_B the server.

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Node_A : Host { }

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Node_B : Host { }

        interface Bus : Connects<Node_A, Node_B> {
            // Every message type of this root namespace, either direction, no state transition.
            [_____lr_____<(hex.equipment.flow.Measurement, himark.servo.ServoCmd, himark.servo.ServoInfo, hobbywing.esc.GetEscID, hobbywing.esc.RawCommand, hobbywing.esc.StatusMsg1, hobbywing.esc.StatusMsg2, hobbywing.esc.StatusMsg3, tmotor.esc.FocCtrl, tmotor.esc.PUSHCAN, tmotor.esc.PUSHSCI, tmotor.esc.ParamCfg, tmotor.esc.ParamGet, volz.servo.ActuatorStatus, xacti.CopterAttStatus, xacti.GimbalAttitudeStatus, xacti.GimbalControlData, xacti.GnssStatus, xacti.GnssStatusReq)>]
            struct Messages { }

            // Services: Node_A calls, Node_B responds (RPC shorthand: Call → Return → End).
            (L____________, hobbywing.esc.GetMaintenanceInformation_Response) hobbywing_esc_GetMaintenanceInformation(hobbywing.esc.GetMaintenanceInformation_Request req);
            (L____________, hobbywing.esc.GetMajorConfig_Response) hobbywing_esc_GetMajorConfig(hobbywing.esc.GetMajorConfig_Request req);
            (L____________, hobbywing.esc.SelfTest_Response) hobbywing_esc_SelfTest(hobbywing.esc.SelfTest_Request req);
            (L____________, hobbywing.esc.SetAngle_Response) hobbywing_esc_SetAngle(hobbywing.esc.SetAngle_Request req);
            (L____________, hobbywing.esc.SetBaud_Response) hobbywing_esc_SetBaud(hobbywing.esc.SetBaud_Request req);
            (L____________, hobbywing.esc.SetDirection_Response) hobbywing_esc_SetDirection(hobbywing.esc.SetDirection_Request req);
            (L____________, hobbywing.esc.SetID_Response) hobbywing_esc_SetID(hobbywing.esc.SetID_Request req);
            (L____________, hobbywing.esc.SetLED_Response) hobbywing_esc_SetLED(hobbywing.esc.SetLED_Request req);
            (L____________, hobbywing.esc.SetReportingFrequency_Response) hobbywing_esc_SetReportingFrequency(hobbywing.esc.SetReportingFrequency_Request req);
            (L____________, hobbywing.esc.SetThrottleSource_Response) hobbywing_esc_SetThrottleSource(hobbywing.esc.SetThrottleSource_Request req);
        }

        // ═════════════════════════ DSDL metadata attributes ═════════════════════════

        // AdHoc custom attributes: carried into the generated code as constants attached to the entity.

        /** DSDL type version (major, minor) from the file name. */
        public class VersionAttribute : Attribute { public VersionAttribute(long major, long minor) { } }

        /** @union: a tagged union, exactly one field is present. */
        public class UnionAttribute : Attribute { }

        /** @deprecated: the type is scheduled for removal. */
        public class DeprecatedAttribute : Attribute { }

        /** @sealed: no delimiter header, the layout is final. */
        public class SealedAttribute : Attribute { }

        /** @extent in bytes: the maximum serialized size future versions may grow to. */
        public class ExtentAttribute : Attribute { public ExtentAttribute(long bytes) { } }

        /** The DSDL field is a 16-bit IEEE 754 float (carried as float). */
        public class Float16Attribute : Attribute { }

        /** Explicit DSDL cast mode of the field ("truncated"; saturated is the default). */
        public class CastModeAttribute : Attribute { public CastModeAttribute(string mode) { } }

    }
}
