// Generated by DSDL2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: dronecan/dronecan (15 types) + 1 referenced types of other root namespaces
// DSDL: OpenCyphal v1 .dsdl and DroneCAN .uavcan definitions
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.dsdl {
    /**
        <see cref = 'protocol.CanStats'/>
        <see cref = 'protocol.FlexDebug'/>
        <see cref = 'protocol.GlobalTime'/>
        <see cref = 'protocol.Stats'/>
        <see cref = 'remoteid.ArmStatus'/>
        <see cref = 'remoteid.BasicID'/>
        <see cref = 'remoteid.Location'/>
        <see cref = 'remoteid.OperatorID'/>
        <see cref = 'remoteid.SecureCommand_Request'/>
        <see cref = 'remoteid.SecureCommand_Response'/>
        <see cref = 'remoteid.SelfID'/>
        <see cref = 'remoteid.System'/>
        <see cref = 'sensors.hygrometer.Hygrometer'/>
        <see cref = 'sensors.magnetometer.MagneticFieldStrengthHiRes'/>
        <see cref = 'sensors.rc.RCInput'/>
        <see cref = 'sensors.rpm.RPM'/>
    */
    public interface dronecan_dronecan {

        // Fallback caps for anything without an explicit [D(N)]; DSDL states every capacity, so this is only a floor.
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        /**
        Namespace dronecan.protocol
        */
        public struct protocol {

            /**
            Monitor the stats of physical layer on the node
            */
            public class CanStats {
                public const uint fixed_port_id = 343;
                /**
                interface number
                */
                byte Interface;
                /**
                number of tx requests
                */
                uint tx_requests;
                /**
                number of tx requests rejected
                */
                ushort tx_rejected;
                /**
                number of tx requests overflow
                */
                ushort tx_overflow;
                /**
                number of tx requests success
                */
                ushort tx_success;
                /**
                number of tx requests timedout
                */
                ushort tx_timedout;
                /**
                number of tx requests aborted
                */
                ushort tx_abort;
                /**
                number of rx received
                */
                uint rx_received;
                /**
                number of rx overflow
                */
                ushort rx_overflow;
                /**
                number of rx errors
                */
                ushort rx_errors;
                /**
                number of busoff errors
                */
                ushort busoff_errors;
            }

            /**
            flexible debug message for development purposes
            vendors can reserve a range of IDs for their products, reservation are in blocks of 10
            */
            public class FlexDebug {
                public const uint fixed_port_id = 16371;
                public const ushort RESERVATION_SIZE = 10;
                public const ushort AM32_RESERVE_START = 100;
                public const ushort MLRS_RESERVE_START = 110;
                ushort id;
                [D(255)] byte[,,] u8;
            }

            /**
            provide global timestamp, time since 1/1/1970 in microseconds should only be broadcast once a reliable time
            base (GPS or equivalent) is known
            */
            public class GlobalTime {
                public const uint fixed_port_id = 344;
                /**
                DSDL type uavcan.Timestamp (microsecond timestamp) is modelled as an AdHoc DateTime.
                */
                DateTime timestamp;
            }

            /**
            monitor the status of the DroneCAN Protocol decoder on the node
            */
            public class Stats {
                public const uint fixed_port_id = 342;
                /**
                Number of transmitted frames
                */
                uint tx_frames;
                /**
                Number of errors during transmission
                */
                ushort tx_errors;
                /**
                Number of received frames
                */
                uint rx_frames;
                /**
                Number of out-of-memory errors
                */
                ushort rx_error_oom;
                /**
                Number of internal errors
                */
                ushort rx_error_internal;
                /**
                Number of missed start bits
                */
                ushort rx_error_missed_start;
                /**
                Number of wrong toggle bits
                */
                ushort rx_error_wrong_toggle;
                /**
                Number of frames that were too short
                */
                ushort rx_error_short_frame;
                /**
                Number of frames with bad CRC
                */
                ushort rx_error_bad_crc;
                /**
                Number of frames with wrong address
                */
                ushort rx_ignored_wrong_address;
                /**
                Number of frames that were not wanted
                */
                ushort rx_ignored_not_wanted;
                /**
                Number of frames with unexpected TID
                */
                ushort rx_ignored_unexpected_tid;
            }
        }

        /**
        Namespace dronecan.remoteid
        */
        public struct remoteid {

            /**
            DroneCAN version of MAVLink OPEN_DRONE_ID_ARM_STATUS see MAVLink XML for detailed description
            */
            public class ArmStatus {
                public const uint fixed_port_id = 20035;
                public const byte ODID_ARM_STATUS_GOOD_TO_ARM = 0;
                public const byte ODID_ARM_STATUS_FAIL_GENERIC = 1;
                byte status;
                [D(50)] byte[,,] error;
            }

            /**
            DroneCAN version of MAVLink OPEN_DRONE_ID_BASIC_ID see MAVLink XML for detailed description
            */
            public class BasicID {
                public const uint fixed_port_id = 20030;
                public const byte ODID_ID_TYPE_NONE = 0;
                public const byte ODID_ID_TYPE_SERIAL_NUMBER = 1;
                public const byte ODID_ID_TYPE_CAA_REGISTRATION_ID = 2;
                public const byte ODID_ID_TYPE_UTM_ASSIGNED_UUID = 3;
                public const byte ODID_ID_TYPE_SPECIFIC_SESSION_ID = 4;
                /**
                No UA (Unmanned Aircraft) type defined
                */
                public const byte ODID_UA_TYPE_NONE = 0;
                /**
                Aeroplane/Airplane. Fixed wing
                */
                public const byte ODID_UA_TYPE_AEROPLANE = 1;
                /**
                Helicopter or multirotor
                */
                public const byte ODID_UA_TYPE_HELICOPTER_OR_MULTIROTOR = 2;
                /**
                Gyroplane
                */
                public const byte ODID_UA_TYPE_GYROPLANE = 3;
                /**
                VTOL (Vertical Take-Off and Landing). Fixed wing aircraft that can take off vertically
                */
                public const byte ODID_UA_TYPE_HYBRID_LIFT = 4;
                /**
                Ornithopter
                */
                public const byte ODID_UA_TYPE_ORNITHOPTER = 5;
                /**
                Glider
                */
                public const byte ODID_UA_TYPE_GLIDER = 6;
                /**
                Kite
                */
                public const byte ODID_UA_TYPE_KITE = 7;
                /**
                Free Balloon
                */
                public const byte ODID_UA_TYPE_FREE_BALLOON = 8;
                /**
                Captive Balloon
                */
                public const byte ODID_UA_TYPE_CAPTIVE_BALLOON = 9;
                /**
                Airship. E.g. a blimp
                */
                public const byte ODID_UA_TYPE_AIRSHIP = 10;
                /**
                Free Fall/Parachute (unpowered)
                */
                public const byte ODID_UA_TYPE_FREE_FALL_PARACHUTE = 11;
                /**
                Rocket
                */
                public const byte ODID_UA_TYPE_ROCKET = 12;
                /**
                Tethered powered aircraft
                */
                public const byte ODID_UA_TYPE_TETHERED_POWERED_AIRCRAFT = 13;
                /**
                Ground Obstacle
                */
                public const byte ODID_UA_TYPE_GROUND_OBSTACLE = 14;
                /**
                Other type of aircraft not listed earlier
                */
                public const byte ODID_UA_TYPE_OTHER = 15;
                [D(20)] byte[,,] id_or_mac;
                byte id_type;
                byte ua_type;
                [D(20)] byte[,,] uas_id;
            }

            /**
            DroneCAN version of MAVLink OPEN_DRONE_ID_LOCATION see MAVLink XML for detailed description
            */
            public class Location {
                public const uint fixed_port_id = 20031;
                /**
                The status of the (UA) Unmanned Aircraft is undefined
                */
                public const byte ODID_STATUS_UNDECLARED = 0;
                /**
                The UA is on the ground
                */
                public const byte ODID_STATUS_GROUND = 1;
                /**
                The UA is in the air
                */
                public const byte ODID_STATUS_AIRBORNE = 2;
                /**
                The UA is having an emergency
                */
                public const byte ODID_STATUS_EMERGENCY = 3;
                /**
                The height field is relative to the take-off location
                */
                public const byte ODID_HEIGHT_REF_OVER_TAKEOFF = 0;
                /**
                The height field is relative to ground
                */
                public const byte ODID_HEIGHT_REF_OVER_GROUND = 1;
                /**
                The horizontal accuracy is unknown
                */
                public const byte ODID_HOR_ACC_UNKNOWN = 0;
                /**
                The horizontal accuracy is smaller than 10 Nautical Miles. 18.52 km
                */
                public const byte ODID_HOR_ACC_10NM = 1;
                /**
                The horizontal accuracy is smaller than 4 Nautical Miles. 7.408 km
                */
                public const byte ODID_HOR_ACC_4NM = 2;
                /**
                The horizontal accuracy is smaller than 2 Nautical Miles. 3.704 km
                */
                public const byte ODID_HOR_ACC_2NM = 3;
                /**
                The horizontal accuracy is smaller than 1 Nautical Miles. 1.852 km
                */
                public const byte ODID_HOR_ACC_1NM = 4;
                /**
                The horizontal accuracy is smaller than 0.5 Nautical Miles. 926 m
                */
                public const byte ODID_HOR_ACC_0_5NM = 5;
                /**
                The horizontal accuracy is smaller than 0.3 Nautical Miles. 555.6 m
                */
                public const byte ODID_HOR_ACC_0_3NM = 6;
                /**
                The horizontal accuracy is smaller than 0.1 Nautical Miles. 185.2 m
                */
                public const byte ODID_HOR_ACC_0_1NM = 7;
                /**
                The horizontal accuracy is smaller than 0.05 Nautical Miles. 92.6 m
                */
                public const byte ODID_HOR_ACC_0_05NM = 8;
                /**
                The horizontal accuracy is smaller than 30 meter
                */
                public const byte ODID_HOR_ACC_30_METER = 9;
                /**
                The horizontal accuracy is smaller than 10 meter
                */
                public const byte ODID_HOR_ACC_10_METER = 10;
                /**
                The horizontal accuracy is smaller than 3 meter
                */
                public const byte ODID_HOR_ACC_3_METER = 11;
                /**
                The horizontal accuracy is smaller than 1 meter
                */
                public const byte ODID_HOR_ACC_1_METER = 12;
                /**
                The vertical accuracy is unknown
                */
                public const byte ODID_VER_ACC_UNKNOWN = 0;
                /**
                The vertical accuracy is smaller than 150 meter
                */
                public const byte ODID_VER_ACC_150_METER = 1;
                /**
                The vertical accuracy is smaller than 45 meter
                */
                public const byte ODID_VER_ACC_45_METER = 2;
                /**
                The vertical accuracy is smaller than 25 meter
                */
                public const byte ODID_VER_ACC_25_METER = 3;
                /**
                The vertical accuracy is smaller than 10 meter
                */
                public const byte ODID_VER_ACC_10_METER = 4;
                /**
                The vertical accuracy is smaller than 3 meter
                */
                public const byte ODID_VER_ACC_3_METER = 5;
                /**
                The vertical accuracy is smaller than 1 meter
                */
                public const byte ODID_VER_ACC_1_METER = 6;
                /**
                The speed accuracy is unknown
                */
                public const byte ODID_SPEED_ACC_UNKNOWN = 0;
                /**
                The speed accuracy is smaller than 10 meters per second
                */
                public const byte ODID_SPEED_ACC_10_METERS_PER_SECOND = 1;
                /**
                The speed accuracy is smaller than 3 meters per second
                */
                public const byte ODID_SPEED_ACC_3_METERS_PER_SECOND = 2;
                /**
                The speed accuracy is smaller than 1 meters per second
                */
                public const byte ODID_SPEED_ACC_1_METERS_PER_SECOND = 3;
                /**
                The speed accuracy is smaller than 0.3 meters per second
                */
                public const byte ODID_SPEED_ACC_0_3_METERS_PER_SECOND = 4;
                /**
                The timestamp accuracy is smaller than or equal to 0.1 second
                */
                public const byte ODID_TIME_ACC_0_1_SECOND = 1;
                /**
                The timestamp accuracy is smaller than or equal to 0.2 second
                */
                public const byte ODID_TIME_ACC_0_2_SECOND = 2;
                /**
                The timestamp accuracy is smaller than or equal to 0.3 second
                */
                public const byte ODID_TIME_ACC_0_3_SECOND = 3;
                /**
                The timestamp accuracy is smaller than or equal to 0.4 second
                */
                public const byte ODID_TIME_ACC_0_4_SECOND = 4;
                /**
                The timestamp accuracy is smaller than or equal to 0.5 second
                */
                public const byte ODID_TIME_ACC_0_5_SECOND = 5;
                /**
                The timestamp accuracy is smaller than or equal to 0.6 second
                */
                public const byte ODID_TIME_ACC_0_6_SECOND = 6;
                /**
                The timestamp accuracy is smaller than or equal to 0.7 second
                */
                public const byte ODID_TIME_ACC_0_7_SECOND = 7;
                /**
                The timestamp accuracy is smaller than or equal to 0.8 second
                */
                public const byte ODID_TIME_ACC_0_8_SECOND = 8;
                /**
                The timestamp accuracy is smaller than or equal to 0.9 second
                */
                public const byte ODID_TIME_ACC_0_9_SECOND = 9;
                /**
                The timestamp accuracy is smaller than or equal to 1.0 second
                */
                public const byte ODID_TIME_ACC_1_0_SECOND = 10;
                /**
                The timestamp accuracy is smaller than or equal to 1.1 second
                */
                public const byte ODID_TIME_ACC_1_1_SECOND = 11;
                /**
                The timestamp accuracy is smaller than or equal to 1.2 second
                */
                public const byte ODID_TIME_ACC_1_2_SECOND = 12;
                /**
                The timestamp accuracy is smaller than or equal to 1.3 second
                */
                public const byte ODID_TIME_ACC_1_3_SECOND = 13;
                /**
                The timestamp accuracy is smaller than or equal to 1.4 second
                */
                public const byte ODID_TIME_ACC_1_4_SECOND = 14;
                /**
                The timestamp accuracy is smaller than or equal to 1.5 second
                */
                public const byte ODID_TIME_ACC_1_5_SECOND = 15;
                [D(20)] byte[,,] id_or_mac;
                byte status;
                /**
                centi-deg, 0-35999
                */
                ushort direction;
                /**
                cm/s, max 25425, if unknown use 25500
                */
                ushort speed_horizontal;
                /**
                positive up, max +/-6200, if unknown use 6300
                */
                short speed_vertical;
                /**
                degE7
                */
                int latitude;
                /**
                degE7
                */
                int longitude;
                /**
                meters, for unknown use -1000, ref is 29.92inHg or 1013.2mb
                */
                float altitude_barometric;
                /**
                meters, for unknown use -1000, WGS84
                */
                float altitude_geodetic;
                byte height_reference;
                /**
                meters, for unknown use -1000
                */
                float height;
                byte horizontal_accuracy;
                byte vertical_accuracy;
                byte barometer_accuracy;
                byte speed_accuracy;
                /**
                seconds after the full hour with reference to UTC time. Use 0xFFFF if unknown
                */
                float timestamp;
                byte timestamp_accuracy;
            }

            /**
            DroneCAN version of MAVLink OPEN_DRONE_ID_OPERATOR_ID see MAVLink XML for detailed description
            */
            public class OperatorID {
                public const uint fixed_port_id = 20034;
                /**
                CAA (Civil Aviation Authority) registered operator ID
                */
                public const byte ODID_OPERATOR_ID_TYPE_CAA = 0;
                [D(20)] byte[,,] id_or_mac;
                byte operator_id_type;
                [D(20)] byte[,,] operator_id;
            }

            /**
            Request of service dronecan.remoteid.SecureCommand
            DroneCAN version of MAVLink2 SECURE_COMMAND. Please see MAVLink2 spec for more details
            */
            public class SecureCommand_Request {
                public const uint fixed_port_id = 64;
                public const uint SECURE_COMMAND_GET_SESSION_KEY = 0;
                public const uint SECURE_COMMAND_GET_REMOTEID_SESSION_KEY = 1;
                public const uint SECURE_COMMAND_REMOVE_PUBLIC_KEYS = 2;
                public const uint SECURE_COMMAND_GET_PUBLIC_KEYS = 3;
                public const uint SECURE_COMMAND_SET_PUBLIC_KEYS = 4;
                public const uint SECURE_COMMAND_GET_REMOTEID_CONFIG = 5;
                public const uint SECURE_COMMAND_SET_REMOTEID_CONFIG = 6;
                uint sequence; // physics: monotonic and large (counter/uptime/sequence) → varint LOSES past 268 435 455; keep fixed width
                uint operation;
                byte sig_length;
                [D(220)] byte[,,] data;
            }

            /**
            Response of service dronecan.remoteid.SecureCommand
            DroneCAN version of MAVLink2 SECURE_COMMAND. Please see MAVLink2 spec for more details
            */
            public class SecureCommand_Response {
                public const uint fixed_port_id = 64;
                public const byte RESULT_ACCEPTED = 0;
                public const byte RESULT_TEMPORARILY_REJECTED = 1;
                public const byte RESULT_DENIED = 2;
                public const byte RESULT_UNSUPPORTED = 3;
                public const byte RESULT_FAILED = 4;
                uint sequence; // physics: monotonic and large (counter/uptime/sequence) → varint LOSES past 268 435 455; keep fixed width
                uint operation;
                byte result;
                [D(220)] byte[,,] data;
            }

            /**
            DroneCAN version of MAVLink OPEN_DRONE_ID_SELF_ID see MAVLink XML for detailed description
            */
            public class SelfID {
                public const uint fixed_port_id = 20032;
                /**
                Free-form text description of the purpose of the flight
                */
                public const byte ODID_DESC_TYPE_TEXT = 0;
                [D(20)] byte[,,] id_or_mac;
                byte description_type;
                [D(23)] byte[,,] description;
            }

            /**
            DroneCAN version of MAVLink OPEN_DRONE_ID_SYSTEM see MAVLink XML for detailed description
            */
            public class System {
                public const uint fixed_port_id = 20033;
                /**
                The location of the operator is the same as the take-off location
                */
                public const byte ODID_OPERATOR_LOCATION_TYPE_TAKEOFF = 0;
                /**
                The location of the operator is based on live GNSS data
                */
                public const byte ODID_OPERATOR_LOCATION_TYPE_LIVE_GNSS = 1;
                /**
                The location of the operator is a fixed location
                */
                public const byte ODID_OPERATOR_LOCATION_TYPE_FIXED = 2;
                public const byte ODID_CLASSIFICATION_TYPE_EU = 0;
                /**
                The category for the UA, according to the EU specification, is undeclared
                */
                public const byte ODID_CATEGORY_EU_UNDECLARED = 0;
                /**
                The category for the UA, according to the EU specification, is the Open category
                */
                public const byte ODID_CATEGORY_EU_OPEN = 1;
                /**
                The category for the UA, according to the EU specification, is the Specific category
                */
                public const byte ODID_CATEGORY_EU_SPECIFIC = 2;
                /**
                The category for the UA, according to the EU specification, is the Certified category
                */
                public const byte ODID_CATEGORY_EU_CERTIFIED = 3;
                /**
                The class for the UA, according to the EU specification, is undeclared
                */
                public const byte ODID_CLASS_EU_UNDECLARED = 0;
                /**
                The class for the UA, according to the EU specification, is Class 0
                */
                public const byte ODID_CLASS_EU_CLASS_0 = 1;
                /**
                The class for the UA, according to the EU specification, is Class 1
                */
                public const byte ODID_CLASS_EU_CLASS_1 = 2;
                /**
                The class for the UA, according to the EU specification, is Class 2
                */
                public const byte ODID_CLASS_EU_CLASS_2 = 3;
                /**
                The class for the UA, according to the EU specification, is Class 3
                */
                public const byte ODID_CLASS_EU_CLASS_3 = 4;
                /**
                The class for the UA, according to the EU specification, is Class 4
                */
                public const byte ODID_CLASS_EU_CLASS_4 = 5;
                /**
                The class for the UA, according to the EU specification, is Class 5
                */
                public const byte ODID_CLASS_EU_CLASS_5 = 6;
                /**
                The class for the UA, according to the EU specification, is Class 6
                */
                public const byte ODID_CLASS_EU_CLASS_6 = 7;
                [D(20)] byte[,,] id_or_mac;
                byte operator_location_type;
                byte classification_type;
                /**
                degE7
                */
                int operator_latitude;
                /**
                degE7
                */
                int operator_longitude;
                /**
                default 1
                */
                ushort area_count; // physics: monotonic and large (counter/uptime/sequence) → varint LOSES past 268 435 455; keep fixed width
                /**
                meters
                */
                ushort area_radius;
                /**
                meters, use -1000 if unknown, WGS84
                */
                float area_ceiling;
                /**
                meters, use -1000 if unknown, WGS84
                */
                float area_floor;
                byte category_eu;
                byte class_eu;
                /**
                meters, use -1000 if unknown, WGS84
                */
                float operator_altitude_geo;
                /**
                Unix seconds since 00:00:00 01/01/2019
                */
                uint timestamp; // physics: monotonic and large (counter/uptime/sequence) → varint LOSES past 268 435 455; keep fixed width
            }
        }

        /**
        Namespace dronecan.sensors
        */
        public struct sensors {

            /**
            Namespace dronecan.sensors.hygrometer
            */
            public struct hygrometer {

                /**
                support for hygrometer sensors
                */
                public class Hygrometer {
                    public const uint fixed_port_id = 1032;
                    /**
                    temperature in degrees C, use NaN if not available
                    */
                    [Float16] float temperature;
                    /**
                    humidity as percentage
                    */
                    [Float16] float humidity;
                    /**
                    id of humidity sensor within this CAN node. Use 0 for first sensor
                    */
                    byte id;
                }
            }

            /**
            Namespace dronecan.sensors.magnetometer
            */
            public struct magnetometer {

                /**
                Magnetic field readings, in Gauss, in body frame, high resolution version
                */
                public class MagneticFieldStrengthHiRes {
                    public const uint fixed_port_id = 1043;
                    byte sensor_id;
                    [D(3)] float[] magnetic_field_ga;
                }
            }

            /**
            Namespace dronecan.sensors.rc
            */
            public struct rc {

                /**
                RC channels and basic link statistics
                */
                public class RCInput {
                    public const uint fixed_port_id = 1140;
                    /**
                    quality field is valid
                    */
                    public const byte STATUS_QUALITY_VALID = 1;
                    /**
                    receiver has lost contact with transmitter
                    */
                    public const byte STATUS_FAILSAFE = 2;
                    /**
                    mask of 3 bits (4+8+16) to indicate the type of data carried in the quality field, see QUALITY_TYPE enum
                    */
                    public const byte STATUS_QUALITY_TYPE = 28;
                    /**
                    quality field represents RSSI in scaled units, 0 is no signal, 255 is "full" signal
                    */
                    public const byte QUALITY_TYPE_RSSI = 0;
                    /**
                    quality field represents LQ in percent in bits 1-7 (0 is no signal, 100 is 100% link quality) and active
                    antenna in bit 8
                    */
                    public const byte QUALITY_TYPE_LQ_ACTIVE_ANTENNA = 4;
                    /**
                    quality field represents RSSI in inverted dBm, 0 is no signal, 1 = -1 dBm, 255 = -255 dBm
                    */
                    public const byte QUALITY_TYPE_RSSI_DBM = 8;
                    /**
                    quality field represents SNR in device dependent units, shifted by 128
                    */
                    public const byte QUALITY_TYPE_SNR = 12;
                    /**
                    quality field represents uplink power in units of 5 mW
                    */
                    public const byte QUALITY_TYPE_TX_POWER = 16;
                    /**
                    bitmask of status bits, enumerated above with STATUS_*
                    */
                    ushort status;
                    /**
                    see descriptions for status bits STATUS_QUALITY_VALID, STATUS_QUALITY_LQ, STATUS_QUALITY_SNR
                    */
                    byte quality;
                    /**
                    ID of this RC input device
                    */
                    [MinMax(0, 15)] byte id;
                    /**
                    RC channel values between 0 and 4095, values are in PWM microseconds, 1500 represents the mid position
                    */
                    [MinMax(0, 4095), D(32)] ushort[,,] rcin;
                }
            }

            /**
            Namespace dronecan.sensors.rpm
            */
            public struct rpm {

                /**
                RPM reading in revolutions per minute
                */
                public class RPM {
                    public const uint fixed_port_id = 1045;
                    /**
                    Sensor is not healthy
                    */
                    public const ushort FLAGS_UNHEALTHY = 1;
                    byte sensor_id;
                    ushort flags;
                    float rpm;
                }
            }
        }

        /**
        Namespace uavcan
        */
        public struct uavcan {

            /**
            Global timestamp in microseconds, 7 bytes.
            Use this data type for timestamp fields in messages, like follows: uavcan.Timestamp timestamp
            Referenced from another root namespace; used as a sub-pack only.
            Fields of this DSDL type are emitted as an AdHoc DateTime, so this pack itself is normally unused.
            */
            public class Timestamp {
                public const ulong UNKNOWN = 0;
                /**
                Microseconds
                */
                [CastMode("truncated"), MinMax(0, 72057594037927935)] ulong usec;
            }
        }

        // ═════════════════════════ demo topology ═════════════════════════

        // DSDL describes data types, not a topology: any node may publish any message subject and any node
        // may serve any service. The demo joins two nodes; Node_A is the service client, Node_B the server.

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Node_A : Host { }

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Node_B : Host { }

        interface Bus : Connects<Node_A, Node_B> {
            // Every message type of this root namespace, either direction, no state transition.
            [_____lr_____<(protocol.CanStats, protocol.FlexDebug, protocol.GlobalTime, protocol.Stats, remoteid.ArmStatus, remoteid.BasicID, remoteid.Location, remoteid.OperatorID, remoteid.SelfID, remoteid.System, sensors.hygrometer.Hygrometer, sensors.magnetometer.MagneticFieldStrengthHiRes, sensors.rc.RCInput, sensors.rpm.RPM)>]
            struct Messages { }

            // Services: Node_A calls, Node_B responds (RPC shorthand: Call → Return → End).
            (L____________, remoteid.SecureCommand_Response) remoteid_SecureCommand(remoteid.SecureCommand_Request req);
        }

        // ═════════════════════════ DSDL metadata attributes ═════════════════════════

        // AdHoc custom attributes: carried into the generated code as constants attached to the entity.

        /** DSDL type version (major, minor) from the file name. */
        public class VersionAttribute : Attribute { public VersionAttribute(long major, long minor) { } }

        /** @union: a tagged union, exactly one field is present. */
        public class UnionAttribute : Attribute { }

        /** @deprecated: the type is scheduled for removal. */
        public class DeprecatedAttribute : Attribute { }

        /** @sealed: no delimiter header, the layout is final. */
        public class SealedAttribute : Attribute { }

        /** @extent in bytes: the maximum serialized size future versions may grow to. */
        public class ExtentAttribute : Attribute { public ExtentAttribute(long bytes) { } }

        /** The DSDL field is a 16-bit IEEE 754 float (carried as float). */
        public class Float16Attribute : Attribute { }

        /** Explicit DSDL cast mode of the field ("truncated"; saturated is the default). */
        public class CastModeAttribute : Attribute { public CastModeAttribute(string mode) { } }

    }
}
